### PR TITLE
refactor(wakunode2): split setup logic into app module (pt. 1)

### PR DESCRIPTION
**Pull request by LNSD**
# Context

Wakunode2 is the main `nwaku` application. The `apps/wakunode2/wakunode2.nim` file contains a lot of logic that is not tested as part of the CI process (only manually at release time). 

This `refactor(wakunode2): split setup logic into app module` PR refactoring series is part of the groundwork necessary to encapsulate the app logic and make it testable.

# PR specific description

This is the first PR of the `refactor(wakunode2): split setup logic into app module` refactoring series.

> **Note**
> This PR is not merging into the `master` branch. It is merging into `wakunode-develop`.

- [x] Added `apps/wakunode2/app.nim` module.
- [x] Temporarily `include` the app module into the main file to avoid compilation errors keeping backward compatibility. This generally is a bad practice. Here it is the only solution since I don't want to make these methods' visibility public (I want it to be private to the `app.nim` module).
- [x] Moved some of the setup methods from the main file to the app module:
	+ The database (SQLite) related setup logic.
	+ The peer storage-related setup logic.
	+ The Waku Archive setup logic.

### CODE REVIEW

**Review by rymnc — APPROVED** [review]
LGTM

File: apps/wakunode2/app.nim [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+      trace "resolving", domain=domain
+      let resolved = await dnsResolver.resolveTxt(domain)
+      return resolved[0] # Use only first answer
+
+    var wakuDnsDiscovery = WakuDnsDiscovery.init(dnsDiscoveryUrl, resolver)
+    if wakuDnsDiscovery.isOk():
+      return wakuDnsDiscovery.get().findPeers()
+        .mapErr(proc (e: cstring): string = $e)
+    else:
+      warn "Failed to init Waku DNS discovery"
```
Comment (Ivansete-status) [inline apps/wakunode2/app.nim:192]: Although beyond the scope of the PR but, may append the error value, if any?

**Review by Ivansete-status — APPROVED** [review]

**Review by jm-clius — APPROVED** [review]
LGTM!
